export enum PromptKey {
  REVISOR_PERIODICO = 'REVISOR_PERIODICO',
  REVISOR_DE_ARTIGOS = 'REVISOR_DE_ARTIGOS',
  TOP_JOURNALS_TRADUTOR = 'TOP_JOURNALS_TRADUTOR',
  REVISOR_DE_TEXTO = 'REVISOR_DE_TEXTO',
  NORMAS_APA = 'NORMAS_APA',
}